---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: ruby-space
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: 'postgres:15'
          env:
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: admin
          ports:
            - containerPort: 5432
