apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-app
  namespace: ruby-space
  labels:
    app: ruby
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ruby
  template:
    metadata:
      labels:
        app: ruby
    spec:
      containers:
      - name: ruby-app
        image: dhanushnadar/ruby-app:v3
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_HOST
          value: "postgresql"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "root"
        - name: POSTGRES_PASSWORD
          value: "admin"
        - name: POSTGRES_DB
          value: "ruby_getting_started"
        command: ["/app/init-db.sh"]
